close all;
figure;
hold on;

data = [1 61 23; 2 81 7; 3 42 40; 4 51 32];
% dataYes = [61 81 42 51];
% dataNo = [23 7 40 32];
%axis([1 5 0 90]);
hBar = bar(data(:,2:3));
grid ;

hBar(1).EdgeColor = [.45 .45 .45];
hBar(1).FaceColor = [0.87 0.97 1];
hBar(1).LineWidth = 1;


hBar(2).EdgeColor = [.45 .45 .45];
hBar(2).FaceColor = [0.99 0.98 0.74];
hBar(2).LineWidth = 1;

%hTitle  = title ('Subjective evaluation results');
%hXLabel = xlabel('Episodes'                     );
hYLabel = ylabel('Number of subjects'                      );

hLegend = legend( ...
  [hBar(1), hBar(2)], ...
  'Yes' , ...
  'No'      , ...
  'location', [.83 .8 0 0.1] );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hYLabel], ...
    'FontName'   , 'Helvetica');
set([hLegend, gca]             , ...
    'FontSize'   , 10           );
set([hYLabel]  , ...
    'FontSize'   , 12          );
% set( hTitle                    , ...
%     'FontSize'   , 12          , ...
%     'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'off'      , ...
  'XTick'       , (0:1:8)      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XTickLabel'  , {'' 'Reuse' 'Ease of use' 'What to say to system'  'System understood' }, ...
  'LineWidth'   , 1         );

% p = get(hTitle,'Position');
% set(hTitle,'Position',[p(1) p(2)*1.02 p(3)]);

set(gcf, 'PaperPositionMode', 'auto');
set(gcf, 'PaperPosition', [0 0 7 5]); %Position plot at left hand corner with width 5 and height 5.
set(gcf, 'PaperSize', [7 5]); %Set the paper to
saveas(gcf, 'subjective','pdf');
